# This is a basic workflow to help you get started with Actions

name: Publishing package to pypi.

# Controls when the workflow will run
on: 
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup up python
        id: setup-python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Bump version
        run: poetry version patch
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.13
        with:
          python_version: "3.8"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
