# This is a basic workflow to help you get started with Actions

name: Publishing package to pypi.

# Controls when the workflow will run
on: 
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.13
        with:
          python_version: "3.7.1"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
